// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapigen

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Comment defines model for Comment.
type Comment struct {
	Body      string             `json:"body"`
	CreatedAt openapi_types.Date `json:"createdAt"`
	Id        int32              `json:"id"`
	PostId    string             `json:"postId"`
	UpdatedAt openapi_types.Date `json:"updatedAt"`
	UserId    string             `json:"userId"`
}

// JWTResponse defines model for JWTResponse.
type JWTResponse struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
}

// Post defines model for Post.
type Post struct {
	Body      string             `json:"body"`
	Comments  []Comment          `json:"comments"`
	CreatedAt openapi_types.Date `json:"createdAt"`
	Id        int32              `json:"id"`
	LikeCount int32              `json:"likeCount"`
	UpdatedAt openapi_types.Date `json:"updatedAt"`
	User      *User              `json:"user,omitempty"`
	UserId    string             `json:"userId"`
}

// User defines model for User.
type User struct {
	Bio        *string `json:"bio,omitempty"`
	CoverImage *string `json:"coverImage,omitempty"`

	// Email Email address of the user
	Email        *openapi_types.Email `json:"email,omitempty"`
	FollowingIds *[]int32             `json:"followingIds,omitempty"`

	// Id Unique ID of the user
	Id *int32 `json:"id,omitempty"`

	// Name Full name of the user
	Name         *string `json:"name,omitempty"`
	ProfileImage *string `json:"profileImage,omitempty"`

	// Username Unique username for the user
	Username *string `json:"username,omitempty"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	// Email Email address of the user
	Email openapi_types.Email `json:"email"`

	// Name Full name of the user
	Name string `json:"name"`

	// Password User password
	Password string `json:"password"`

	// Username Unique username for the user
	Username string `json:"username"`
}

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	// Bio User biography
	Bio        *string `json:"bio,omitempty"`
	CoverImage *string `json:"coverImage,omitempty"`

	// Name Full name of the user
	Name         string  `json:"name"`
	ProfileImage *string `json:"profileImage,omitempty"`

	// Username Unique username for the user
	Username string `json:"username"`
}

// CommentsParams defines parameters for Comments.
type CommentsParams struct {
	// PostId ID of the post
	PostId *int32 `form:"postId,omitempty" json:"postId,omitempty"`
}

// UnfollowJSONBody defines parameters for Unfollow.
type UnfollowJSONBody struct {
	UserId *int32 `json:"userId,omitempty"`
}

// FollowJSONBody defines parameters for Follow.
type FollowJSONBody struct {
	UserId *int32 `json:"userId,omitempty"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Password *string              `json:"password,omitempty"`
}

// PostsParams defines parameters for Posts.
type PostsParams struct {
	// UserId ID of the user
	UserId *int32 `form:"userId,omitempty" json:"userId,omitempty"`
}

// CreatePostJSONBody defines parameters for CreatePost.
type CreatePostJSONBody struct {
	// Body Текст поста
	Body string `json:"body"`
}

// UnfollowJSONRequestBody defines body for Unfollow for application/json ContentType.
type UnfollowJSONRequestBody UnfollowJSONBody

// FollowJSONRequestBody defines body for Follow for application/json ContentType.
type FollowJSONRequestBody FollowJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody CreatePostJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreateRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение информации о комментариях к посту
	// (GET /comments)
	Comments(ctx echo.Context, params CommentsParams) error
	// Процесс отписки от пользователя
	// (DELETE /follow)
	Unfollow(ctx echo.Context) error
	// Процесс подписки на пользователя
	// (POST /follow)
	Follow(ctx echo.Context) error
	// Authenticate user
	// (POST /login)
	Login(ctx echo.Context) error
	// Logout user
	// (POST /logout)
	Logout(ctx echo.Context) error
	// Получение информации о постах
	// (GET /posts)
	Posts(ctx echo.Context, params PostsParams) error
	// Создание поста
	// (POST /posts)
	CreatePost(ctx echo.Context) error
	// Get post by ID
	// (GET /posts/{id})
	PostById(ctx echo.Context, id int32) error
	// Create a new user
	// (POST /register)
	CreateUser(ctx echo.Context) error
	// List all users
	// (GET /users)
	ListUsers(ctx echo.Context) error
	// Get current user details
	// (GET /users/current)
	GetCurrentUser(ctx echo.Context) error
	// Update user
	// (PUT /users/current)
	UpdateUser(ctx echo.Context) error
	// Get user by ID
	// (GET /users/{id})
	GetUser(ctx echo.Context, id int32) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Comments converts echo context to params.
func (w *ServerInterfaceWrapper) Comments(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CommentsParams
	// ------------- Optional query parameter "postId" -------------

	err = runtime.BindQueryParameter("form", true, false, "postId", ctx.QueryParams(), &params.PostId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Comments(ctx, params)
	return err
}

// Unfollow converts echo context to params.
func (w *ServerInterfaceWrapper) Unfollow(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Unfollow(ctx)
	return err
}

// Follow converts echo context to params.
func (w *ServerInterfaceWrapper) Follow(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Follow(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// Posts converts echo context to params.
func (w *ServerInterfaceWrapper) Posts(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostsParams
	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameter("form", true, false, "userId", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Posts(ctx, params)
	return err
}

// CreatePost converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePost(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePost(ctx)
	return err
}

// PostById converts echo context to params.
func (w *ServerInterfaceWrapper) PostById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostById(ctx, id)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// ListUsers converts echo context to params.
func (w *ServerInterfaceWrapper) ListUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUsers(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUser(ctx)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/comments", wrapper.Comments)
	router.DELETE(baseURL+"/follow", wrapper.Unfollow)
	router.POST(baseURL+"/follow", wrapper.Follow)
	router.POST(baseURL+"/login", wrapper.Login)
	router.POST(baseURL+"/logout", wrapper.Logout)
	router.GET(baseURL+"/posts", wrapper.Posts)
	router.POST(baseURL+"/posts", wrapper.CreatePost)
	router.GET(baseURL+"/posts/:id", wrapper.PostById)
	router.POST(baseURL+"/register", wrapper.CreateUser)
	router.GET(baseURL+"/users", wrapper.ListUsers)
	router.GET(baseURL+"/users/current", wrapper.GetCurrentUser)
	router.PUT(baseURL+"/users/current", wrapper.UpdateUser)
	router.GET(baseURL+"/users/:id", wrapper.GetUser)

}
